name: picto_frontend
description: "컴퓨터공학 캡스톤 프로젝트"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  textfield_tags: ^3.0.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  animated_text_kit: ^4.2.3
  stomp_dart_client: ^2.1.3
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  flex_seed_scheme: ^3.5.0
  debounce_throttle: ^2.0.0
  dropdown_button2: ^2.3.9
  widget_to_marker: ^1.0.6
  mime: ^2.0.0
  http_parser: ^4.1.2
  custom_info_window: ^1.0.1
  google_maps_cluster_manager_2: ^3.2.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/map_styles/

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
