name: picto_frontend
description: "컴퓨터공학 캡스톤 프로젝트"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  textfield_tags: ^3.0.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  animated_text_kit: ^4.2.3
  stomp_dart_client: ^2.1.3
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  flex_seed_scheme: ^3.5.0
  debounce_throttle: ^2.0.0
  dropdown_button2: ^2.3.9
  widget_to_marker: ^1.0.6
  mime: ^2.0.0
  http_parser: ^4.1.2
  custom_info_window: ^1.0.1
  google_maps_cluster_manager_2: ^3.2.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_spinkit: ^5.2.1
  hive: ^2.2.3
  build_runner: ^2.4.15
  hive_flutter: ^1.1.0
  multi_image_picker_view: ^3.0.0
  file_picker: ^10.1.2
  share_plus: ^10.1.4
  carousel_slider: ^5.0.0
  table_calendar: ^3.2.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  restart_app: ^1.3.2
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/map_styles/

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Medium.ttf
           weight: 500
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 900

     - family: PictoIcons
       fonts:
         - asset: assets/fonts/Picto-Icons.ttf

     - family: NotoSansKR
       fonts:
         - asset: assets/fonts/NotoSansKR-Thin.ttf
           weight: 100
         - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/NotoSansKR-Light.ttf
           weight: 300
         - asset: assets/fonts/NotoSansKR-Regular.ttf
           weight: 400
         - asset: assets/fonts/NotoSansKR-Medium.ttf
           weight: 500
         - asset: assets/fonts/NotoSansKR-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/NotoSansKR-Bold.ttf
           weight: 700
         - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/NotoSansKR-Black.ttf
           weight: 900

